// Timeline data for hero section
export const timelineData = [
	{
		id: 1,
		title: 'তফসিল ঘোষণা',
		status: 'অপেক্ষমান',
		date: '১৫ ডিসেম্বর',
		description: 'নির্বাচন কমিশন কর্তৃক নির্বাচনের তফসিল ঘোষণা',
	},
	{
		id: 2,
		title: 'নির্বাচনী প্রার্থীতার জন্য আবেদনের শেষ তারিখ',
		status: 'অপেক্ষমান',
		date: '১০-২৫ জানুয়ারি',
		description: 'প্রার্থীদের মনোনয়নপত্র জমা দেওয়ার শেষ সময়সীমা',
	},
	{
		id: 3,
		title: 'মনোনয়ন যাচাই-বাছাই',
		status: 'অপেক্ষমান',
		date: '৩০ জানুয়ারি',
		description: 'রিটার্নিং অফিসার কর্তৃক মনোনয়নপত্র যাচাই-বাছাই',
	},
	{
		id: 4,
		title: 'রিটার্নিং কর্মকর্তার সিদ্ধান্তের বিরুদ্ধে আপিল ও শুনানি',
		status: 'অপেক্ষমান',
		date: '৫ ফেব্রুয়ারি',
		description: 'মনোনয়ন বাতিলের বিরুদ্ধে আপিল এবং শুনানি প্রক্রিয়া',
	},
	{
		id: 5,
		title: 'প্রার্থীতা বাতিলের শেষ তারিখ',
		status: 'অপেক্ষমান',
		date: '১০ ফেব্রুয়ারি',
		description: 'প্রার্থীরা স্বেচ্ছায় প্রার্থীতা প্রত্যাহার করতে পারবেন',
	},
	{
		id: 6,
		title: 'প্রতীক বরাদ্দ এবং প্রচার-প্রচারণা শুরুর তারিখ',
		status: 'অপেক্ষমান',
		date: '১২-২৮ ফেব্রুয়ারি',
		description: 'নির্বাচনী প্রতীক বরাদ্দ এবং প্রচারণা কার্যক্রম শুরু',
	},
	{
		id: 7,
		title: 'প্রচার-প্রচারণার শেষ দিন',
		status: 'অপেক্ষমান',
		date: '৫ মার্চ',
		description: 'নির্বাচনী প্রচারণা বন্ধের সময়সীমা',
	},
	{
		id: 8,
		title: 'ভোটগ্রহণ ও ফলাফল প্রকাশ',
		status: 'অপেক্ষমান',
		date: '৭ মার্চ',
		description: 'নির্বাচনের দিন এবং ফলাফল ঘোষণা',
	},
];

// Poll data
export const pollsData = [
	{
		id: 1,
		question: 'আগামী নির্বাচনে কোন দল জিতবে বলে আপনি মনে করেন?',
		creatorName: 'ফয়সাল আহমেদ',
		options: [
			{ id: 'a', text: 'আওয়ামী লীগ', votes: 450, color: '#00A651' },
			{ id: 'b', text: 'বিএনপি', votes: 380, color: '#00923F' },
			{ id: 'c', text: 'জাতীয় পার্টি', votes: 120, color: '#F42A41' },
			{ id: 'd', text: 'অন্যান্য', votes: 50, color: '#666666' },
		],
		totalVotes: 1000,
		active: true,
		endDate: '2025-11-10T23:59:59',
		status: 'upcoming',
	},
	{
		id: 2,
		question: 'নির্বাচনে সবচেয়ে গুরুত্বপূর্ণ ইশু কোনটি?',
		creatorName: 'রাহাত করিম',
		options: [
			{ id: 'a', text: 'অর্থনীতি', votes: 350, color: '#C8102E' },
			{ id: 'b', text: 'দুর্নীতি দমন', votes: 280, color: '#E63946' },
			{ id: 'c', text: 'শিক্ষা', votes: 220, color: '#F77F00' },
			{ id: 'd', text: 'স্বাস্থ্য', votes: 150, color: '#06A77D' },
		],
		totalVotes: 1000,
		active: false,
		endDate: '2025-11-01T23:59:59',
		status: 'ended',
		winnerPhone: '01712345719',
	},
	{
		id: 3,
		question: 'স্থানীয় নির্বাচনে কোন বিষয়টি সবচেয়ে গুরুত্বপূর্ণ?',
		creatorName: 'সাদিয়া খান',
		options: [
			{ id: 'a', text: 'উন্নয়ন প্রকল্প', votes: 320, color: '#2A9D8F' },
			{ id: 'b', text: 'পরিবেশ সুরক্ষা', votes: 280, color: '#E76F51' },
			{ id: 'c', text: 'রাস্তা উন্নয়ন', votes: 240, color: '#F4A261' },
			{ id: 'd', text: 'জনসেবা', votes: 160, color: '#264653' },
		],
		totalVotes: 1000,
		active: true,
		endDate: '2025-11-15T23:59:59',
		status: 'upcoming',
	},
];

// News data
export const newsData = [
	{
		id: 1,
		title: 'নির্বাচন কমিশন নতুন নির্দেশনা জারি করেছে',
		summary:
			'আগামী জাতীয় নির্বাচনে ডিজিটাল প্রচারণার জন্য নতুন নির্দেশনা প্রদান করা হয়েছে...',
		image: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800&h=600&fit=crop',
		date: '২ নভেম্বর ২০২৫',
		category: 'নির্বাচন',
	},
	{
		id: 2,
		title: 'রাজনৈতিক দলগুলোর প্রস্তুতি চলছে',
		summary:
			'সকল রাজনৈতিক দল আসন্ন নির্বাচনের জন্য তাদের প্রস্তুতি সম্পন্ন করছে...',
		image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=600&fit=crop',
		date: '১ নভেম্বর ২০২৫',
		category: 'রাজনীতি',
	},
	{
		id: 3,
		title: 'ভোটার তালিকা হালনাগাদ করা হচ্ছে',
		summary:
			'নির্বাচন কমিশন সকল এলাকায় ভোটার তালিকা হালনাগাদ এবং যাচাই করছে...',
		image: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&h=600&fit=crop',
		date: '৩১ অক্টোবর ২০২৫',
		category: 'নির্বাচন',
	},
	{
		id: 4,
		title: 'ইভিএম মেশিন পরীক্ষা শুরু',
		summary:
			'নির্বাচন কমিশন সকল ইলেকট্রনিক ভোটিং মেশিন পরীক্ষা ও যাচাই শুরু করেছে...',
		image: 'https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?w=800&h=600&fit=crop',
		date: '৩০ অক্টোবর ২০২৫',
		category: 'প্রযুক্তি',
	},
];

// Divisions (8 divisions of Bangladesh)
export const divisionsData = [
	{ id: 'rangpur', name: 'রংপুর', nameEn: 'Rangpur', seats: 30 },
	{ id: 'rajshahi', name: 'রাজশাহী', nameEn: 'Rajshahi', seats: 33 },
	{ id: 'khulna', name: 'খুলনা', nameEn: 'Khulna', seats: 29 },
	{ id: 'barishal', name: 'বরিশাল', nameEn: 'Barishal', seats: 20 },
	{ id: 'sylhet', name: 'সিলেট', nameEn: 'Sylhet', seats: 19 },
	{ id: 'chattogram', name: 'চট্টগ্রাম', nameEn: 'Chattogram', seats: 45 },
	{ id: 'mymensingh', name: 'ময়মনসিংহ', nameEn: 'Mymensingh', seats: 21 },
	{ id: 'dhaka', name: 'ঢাকা', nameEn: 'Dhaka', seats: 47 },
];

// Districts (sample data)
export const districtsData = [
	// Dhaka Division
	{
		id: 'dhaka',
		name: 'ঢাকা',
		nameEn: 'Dhaka',
		divisionId: 'dhaka',
		seats: 20,
	},
	{
		id: 'gazipur',
		name: 'গাজীপুর',
		nameEn: 'Gazipur',
		divisionId: 'dhaka',
		seats: 5,
	},
	{
		id: 'narayanganj',
		name: 'নারায়ণগঞ্জ',
		nameEn: 'Narayanganj',
		divisionId: 'dhaka',
		seats: 4,
	},
	{
		id: 'tangail',
		name: 'টাঙ্গাইল',
		nameEn: 'Tangail',
		divisionId: 'dhaka',
		seats: 8,
	},

	// Chattogram Division
	{
		id: 'chattogram',
		name: 'চট্টগ্রাম',
		nameEn: 'Chattogram',
		divisionId: 'chattogram',
		seats: 16,
	},
	{
		id: 'coxsbazar',
		name: 'কক্সবাজার',
		nameEn: "Cox's Bazar",
		divisionId: 'chattogram',
		seats: 4,
	},
	{
		id: 'comilla',
		name: 'কুমিল্লা',
		nameEn: 'Comilla',
		divisionId: 'chattogram',
		seats: 11,
	},
];

// Seats (sample data)
export const seatsData = [
	// Dhaka seats
	{
		id: 'dhaka-1',
		name: 'ঢাকা-১',
		nameEn: 'Dhaka-1',
		districtId: 'dhaka',
		area: 'দোহার, নবাবগঞ্জ',
	},
	{
		id: 'dhaka-2',
		name: 'ঢাকা-২',
		nameEn: 'Dhaka-2',
		districtId: 'dhaka',
		area: 'কেরানীগঞ্জ',
	},
	{
		id: 'dhaka-3',
		name: 'ঢাকা-৩',
		nameEn: 'Dhaka-3',
		districtId: 'dhaka',
		area: 'সদর, লালবাগ',
	},
	{
		id: 'dhaka-4',
		name: 'ঢাকা-৪',
		nameEn: 'Dhaka-4',
		districtId: 'dhaka',
		area: 'হাজারীবাগ, শ্যামপুর',
	},
	{
		id: 'dhaka-5',
		name: 'ঢাকা-৫',
		nameEn: 'Dhaka-5',
		districtId: 'dhaka',
		area: 'সূত্রাপুর, গেন্ডারিয়া',
	},

	// Gazipur seats
	{
		id: 'gazipur-1',
		name: 'গাজীপুর-১',
		nameEn: 'Gazipur-1',
		districtId: 'gazipur',
		area: 'গাজীপুর সদর',
	},

	// Narayanganj seats
	{
		id: 'narayanganj-1',
		name: 'নারায়ণগঞ্জ-১',
		nameEn: 'Narayanganj-1',
		districtId: 'narayanganj',
		area: 'নারায়ণগঞ্জ সদর',
	},

	// Tangail seats
	{
		id: 'tangail-1',
		name: 'টাঙ্গাইল-১',
		nameEn: 'Tangail-1',
		districtId: 'tangail',
		area: 'টাঙ্গাইল সদর',
	},

	// Chattogram seats
	{
		id: 'chattogram-1',
		name: 'চট্টগ্রাম-১',
		nameEn: 'Chattogram-1',
		districtId: 'chattogram',
		area: 'বন্দর, চকবাজার',
	},
	{
		id: 'chattogram-2',
		name: 'চট্টগ্রাম-২',
		nameEn: 'Chattogram-2',
		districtId: 'chattogram',
		area: 'পাহাড়তলী, পতেঙ্গা',
	},
];

// Political Parties
export const partiesData = [
	{
		id: 'al',
		name: 'বাংলাদেশ আওয়ামী লীগ',
		nameEn: 'Bangladesh Awami League',
		symbol: '🚢',
		symbolName: 'নৌকা',
		color: '#00A651',
		founded: '১৯৪৯',
	},
	{
		id: 'bnp',
		name: 'বাংলাদেশ জাতীয়তাবাদী দল',
		nameEn: 'Bangladesh Nationalist Party',
		symbol: '🌾',
		symbolName: 'ধানের শীষ',
		color: '#00923F',
		founded: '১৯৭৮',
	},
	{
		id: 'jp',
		name: 'জাতীয় পার্টি',
		nameEn: 'Jatiya Party',
		symbol: '🏏',
		symbolName: 'ক্রিকেট স্ট্যাম্প',
		color: '#F42A41',
		founded: '১৯৮৬',
	},
	{
		id: 'jamat',
		name: 'জামায়াতে ইসলামী',
		nameEn: 'Jamaat-e-Islami',
		symbol: '⚖️',
		symbolName: 'দাঁড়িপাল্লা',
		color: '#006747',
		founded: '১৯৪১',
	},
	{
		id: 'independent',
		name: 'স্বতন্ত্র প্রার্থী',
		nameEn: 'Independent',
		symbol: '👤',
		symbolName: 'স্বতন্ত্র',
		color: '#6B7280',
		founded: 'N/A',
	},
];

// Independent Candidate Symbols/Markas
export const independentSymbols = [
	{ id: 'ind-mango', symbol: '🥭', symbolName: 'আম' },
	{ id: 'ind-pineapple', symbol: '🍍', symbolName: 'আনারস' },
	{ id: 'ind-apple', symbol: '🍎', symbolName: 'আপেল' },
	{ id: 'ind-banana', symbol: '🍌', symbolName: 'কলা' },
	{ id: 'ind-coconut', symbol: '🥥', symbolName: 'নারিকেল' },
	{ id: 'ind-football', symbol: '⚽', symbolName: 'ফুটবল' },
	{ id: 'ind-bicycle', symbol: '🚲', symbolName: 'সাইকেল' },
	{ id: 'ind-car', symbol: '🚗', symbolName: 'গাড়ি' },
	{ id: 'ind-plane', symbol: '✈️', symbolName: 'বিমান' },
	{ id: 'ind-book', symbol: '📚', symbolName: 'বই' },
];

// Candidates (sample data)
export const candidatesData = [
	{
		id: '1',
		name: 'মোহাম্মদ রহিম',
		nameEn: 'Mohammad Rahim',
		partyId: 'al',
		seatId: 'dhaka-1',
		age: 45,
		education: 'এমবিএ, ঢাকা বিশ্ববিদ্যালয়',
		experience: 'সাংসদ (২০১৪-২০১৮)',
		image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
	},
	{
		id: '2',
		name: 'আব্দুল করিম',
		nameEn: 'Abdul Karim',
		partyId: 'bnp',
		seatId: 'dhaka-1',
		age: 52,
		education: 'এলএলবি, রাজশাহী বিশ্ববিদ্যালয়',
		experience: 'আইনজীবী (২৫ বছর)',
		image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
	},
	{
		id: '3',
		name: 'ফাতেমা খাতুন',
		nameEn: 'Fatema Khatun',
		partyId: 'jp',
		seatId: 'dhaka-2',
		age: 38,
		education: 'পিএইচডি, অর্থনীতি',
		experience: 'বিশ্ববিদ্যালয় শিক্ষক (১০ বছর)',
		image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
	},
	{
		id: '4',
		name: 'সালমান আহমেদ',
		nameEn: 'Salman Ahmed',
		partyId: 'al',
		seatId: 'dhaka-3',
		age: 41,
		education: 'বিএসসি ইঞ্জিনিয়ারিং, বুয়েট',
		experience: 'উদ্যোক্তা ও ব্যবসায়ী',
		image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
	},
	{
		id: '5',
		name: 'জাহানারা বেগম',
		nameEn: 'Jahanara Begum',
		partyId: 'al',
		seatId: 'dhaka-4',
		age: 48,
		education: 'এমএ, রাজনীতি বিজ্ঞান',
		experience: 'সামাজিক কর্মী (২০ বছর)',
		image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
	},
	{
		id: '6',
		name: 'রফিকুল ইসলাম',
		nameEn: 'Rafiqul Islam',
		partyId: 'bnp',
		seatId: 'dhaka-2',
		age: 55,
		education: 'এমবিবিএস, চট্টগ্রাম মেডিকেল',
		experience: 'চিকিৎসক ও সমাজসেবক',
		image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
	},
	{
		id: '7',
		name: 'নাসরিন সুলতানা',
		nameEn: 'Nasrin Sultana',
		partyId: 'jp',
		seatId: 'dhaka-3',
		age: 43,
		education: 'এলএলএম, ঢাকা বিশ্ববিদ্যালয়',
		experience: 'আইনজীবী ও মানবাধিকার কর্মী',
		image: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop',
	},
	{
		id: '8',
		name: 'কামরুল হাসান',
		nameEn: 'Kamrul Hasan',
		partyId: 'jamat',
		seatId: 'dhaka-4',
		age: 50,
		education: 'বিকম, ঢাকা বিশ্ববিদ্যালয়',
		experience: 'ব্যবসায়ী ও সমাজসেবক',
		image: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
	},
	{
		id: '9',
		name: 'সেলিনা আক্তার',
		nameEn: 'Selina Akter',
		partyId: 'al',
		seatId: 'dhaka-5',
		age: 39,
		education: 'এমএসসি, পদার্থবিজ্ঞান',
		experience: 'শিক্ষক ও গবেষক',
		image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
	},
	{
		id: '10',
		name: 'তানভীর আহমেদ',
		nameEn: 'Tanvir Ahmed',
		partyId: 'bnp',
		seatId: 'dhaka-5',
		age: 46,
		education: 'এমবিএ, আইবিএ',
		experience: 'ব্যাংক ম্যানেজার (১৫ বছর)',
		image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop',
	},
	{
		id: '11',
		name: 'শামসুন নাহার',
		nameEn: 'Shamsun Nahar',
		partyId: 'jp',
		seatId: 'chattogram-1',
		age: 44,
		education: 'বিএ অনার্স, বাংলা সাহিত্য',
		experience: 'সাংবাদিক ও লেখক',
		image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
	},
	{
		id: '12',
		name: 'আনোয়ার হোসেন',
		nameEn: 'Anowar Hossain',
		partyId: 'al',
		seatId: 'chattogram-1',
		age: 53,
		education: 'এলএলবি, চট্টগ্রাম বিশ্ববিদ্যালয়',
		experience: 'সাবেক মেয়র (২০১০-২০১৫)',
		image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop',
	},
	{
		id: '13',
		name: 'রুমানা ফেরদৌসী',
		nameEn: 'Rumana Ferdousi',
		partyId: 'bnp',
		seatId: 'chattogram-2',
		age: 41,
		education: 'এমবিবিএস, ঢাকা মেডিকেল',
		experience: 'চিকিৎসক ও স্বাস্থ্য কর্মী',
		image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop',
	},
	{
		id: '14',
		name: 'মাহবুব আলম',
		nameEn: 'Mahbub Alam',
		partyId: 'jamat',
		seatId: 'chattogram-2',
		age: 49,
		education: 'এমএসসি, কৃষি বিজ্ঞান',
		experience: 'কৃষি উদ্যোক্তা (২০ বছর)',
		image: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=400&h=400&fit=crop',
	},
	{
		id: '15',
		name: 'পারভীন আক্তার',
		nameEn: 'Parvin Akter',
		partyId: 'al',
		seatId: 'gazipur-1',
		age: 37,
		education: 'এমবিএ, নর্থ সাউথ ইউনিভার্সিটি',
		experience: 'উদ্যোক্তা ও নারী নেত্রী',
		image: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop',
	},
	{
		id: '16',
		name: 'শাহজাহান মিয়া',
		nameEn: 'Shahjahan Mia',
		partyId: 'bnp',
		seatId: 'gazipur-1',
		age: 58,
		education: 'বিএ, ঢাকা বিশ্ববিদ্যালয়',
		experience: 'সাবেক সাংসদ (২০০৮-২০১৩)',
		image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop',
	},
	{
		id: '17',
		name: 'লায়লা পারভীন',
		nameEn: 'Laila Parvin',
		partyId: 'jp',
		seatId: 'narayanganj-1',
		age: 42,
		education: 'এমএ, সমাজকল্যাণ',
		experience: 'এনজিও কর্মী (১৮ বছর)',
		image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
	},
	{
		id: '18',
		name: 'হাবিবুর রহমান',
		nameEn: 'Habibur Rahman',
		partyId: 'al',
		seatId: 'narayanganj-1',
		age: 51,
		education: 'এলএলএম, রাজশাহী বিশ্ববিদ্যালয়',
		experience: 'হাইকোর্ট আইনজীবী',
		image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
	},
	{
		id: '19',
		name: 'নূরজাহান বেগম',
		nameEn: 'Nurjahan Begum',
		partyId: 'bnp',
		seatId: 'tangail-1',
		age: 45,
		education: 'এমএসসি, গণিত',
		experience: 'কলেজ অধ্যাপক (২০ বছর)',
		image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
	},
	{
		id: '20',
		name: 'জাকির হোসেন',
		nameEn: 'Zakir Hossain',
		partyId: 'jamat',
		seatId: 'tangail-1',
		age: 54,
		education: 'বিএসসি, কম্পিউটার সায়েন্স',
		experience: 'আইটি উদ্যোক্তা (২৫ বছর)',
		image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
	},
	// Independent Candidates
	{
		id: '21',
		name: 'রাশেদ করিম',
		nameEn: 'Rashed Karim',
		partyId: 'independent',
		symbolId: 'ind-mango',
		seatId: 'dhaka-5',
		age: 42,
		education: 'এমবিএ, আইবিএ',
		experience: 'ব্যবসায়ী (১৫ বছর)',
		image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
	},
	{
		id: '22',
		name: 'সুমাইয়া আক্তার',
		nameEn: 'Sumaiya Akter',
		partyId: 'independent',
		symbolId: 'ind-pineapple',
		seatId: 'dhaka-3',
		age: 36,
		education: 'এমএ, সমাজবিজ্ঞান',
		experience: 'সমাজকর্মী (১২ বছর)',
		image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
	},
	{
		id: '23',
		name: 'ফারুক আহমেদ',
		nameEn: 'Faruk Ahmed',
		partyId: 'independent',
		symbolId: 'ind-bicycle',
		seatId: 'chattogram-1',
		age: 48,
		education: 'এলএলবি, ঢাকা বিশ্ববিদ্যালয়',
		experience: 'আইনজীবী (২০ বছর)',
		image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
	},
	{
		id: '24',
		name: 'নাজমা বেগম',
		nameEn: 'Nazma Begum',
		partyId: 'independent',
		symbolId: 'ind-book',
		seatId: 'chattogram-2',
		age: 40,
		education: 'পিএইচডি, শিক্ষা',
		experience: 'বিশ্ববিদ্যালয় অধ্যাপক (১৫ বছর)',
		image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
	},
	{
		id: '25',
		name: 'আলমগীর হোসেন',
		nameEn: 'Alamgir Hossain',
		partyId: 'independent',
		symbolId: 'ind-football',
		seatId: 'gazipur-1',
		age: 35,
		education: 'বিকম, ঢাকা বিশ্ববিদ্যালয়',
		experience: 'উদ্যোক্তা (১০ বছর)',
		image: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
	},
];

// AI Search suggestions
export const searchSuggestions = [
	'নির্বাচনের তারিখ কবে?',
	'আমার এলাকার প্রার্থী কারা?',
	'ভোটার আইডি কার্ড কিভাবে পাবো?',
	'ভোট কেন্দ্র কোথায়?',
	'কোন দল কোন আসনে প্রতিদ্বন্দ্বিতা করছে?',
	'নির্বাচন কমিশন কি?',
];

// Banner/Poster templates
export const designTemplates = [
	{
		id: 'banner-1',
		type: 'banner',
		name: 'ক্লাসিক ব্যানার',
		dimensions: '1920x1080',
	},
	{
		id: 'poster-1',
		type: 'poster',
		name: 'পোস্টার ডিজাইন',
		dimensions: '1080x1350',
	},
	{
		id: 'social-1',
		type: 'social',
		name: 'সোশ্যাল মিডিয়া পোস্ট',
		dimensions: '1080x1080',
	},
];
